### ISSUE TITLE
Why console.log new r.Signature on every call?

### ISSUE THREAD

**Issue by hems** [layerhq/support#1]
By reading this code i can see on line 65 a new instance of r.Signature is always created.

https://github.com/layerhq/support/blob/master/identity-services-samples/nodejs/layer.js#L65

Do i actually need to create this instance on every request?

It seems to me i could actually that remove that line, and always just use

````jws = r.jws.JWS.sign "RS256", header, claim, privateKey.toString()````

does that make sense?

**Comment by maju6406** [comment]
You can remove that line.  It's only there for debugging purposes.

**Comment by hems** [comment]
awesome! thanks.

here is some pseudo-code that will nearly work for hapijs

http://pastebin.com/xbQ5AVA8

it might not exactly work as i did some "editing" removing my app code, but it's nearly there. 

might be useful for someone.
